jobs:
  build:
    permissions:
      contents: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      id: install-gpg-signing-key
      name: Install GPG signing key
      run: '# Install gpg signing key

        cat <(echo -e "${{ secrets.GPG_SIGNING_SECRET_KEY }}") | gpg --batch --import
        > /dev/null 2>&1

        '
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Decode Keystore
      run: 'mkdir -p gpslogger/keystore

        echo "${{ secrets.KEYSTORE }}" | base64 --decode > gpslogger/keystore/your_signing_keystore.jks

        '
      shell: bash
    - continue-on-error: true
      name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    - continue-on-error: true
      name: Make gradlew executable
      run: chmod +x ./gradlew
    - continue-on-error: true
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
      name: Assemble APK
      run: ./gradlew assembleRelease
    - continue-on-error: true
      name: Sign and Checksum APK
      run: ./gradlew copyFinalAPK -Psigning.gnupg.passphrase=${{ secrets.GPG_SIGNING_PASSWORD
        }} -Psigning.gnupg.executable=gpg
    - continue-on-error: true
      name: List the files
      run: "tree gpslogger/build/outputs/   \nls -lah gpslogger/ \n"
    - continue-on-error: true
      name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Build Artifacts
        path: 'gpslogger/gpslogger-*.apk

          gpslogger/gpslogger-*.apk.asc

          gpslogger/gpslogger-*.apk.SHA256

          '
    - continue-on-error: true
      id: create-release
      if: startsWith(github.ref, 'refs/tags/')
      name: Create a Release
      uses: softprops/action-gh-release@v2
      with:
        files: 'gpslogger/gpslogger-*.apk

          gpslogger/gpslogger-*.apk.asc

          gpslogger/gpslogger-*.apk.SHA256'
        make_latest: true
        prerelease: ${{ contains(github.ref, '-rc') && startsWith(github.ref, 'refs/tags/')
          }}
name: Build and Release App Bundle
on:
  repository_dispatch:
    types: trigger-ga___generate-release-apk.yml
