jobs:
  build:
    defaults:
      run:
        working-directory: assets/generate-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up Docker Layer caching
      uses: satackey/action-docker-layer-caching@v0.0.11
    - continue-on-error: true
      name: Build the static site
      run: docker-compose run --rm --entrypoint "/bin/bash -c 'npm install;npx eleventy'"
        eleventy
    - continue-on-error: true
      name: Setup Github Pages
      uses: actions/configure-pages@v2
    - continue-on-error: true
      name: Upload Github Pages artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: assets/generate-pages/_site
    - continue-on-error: true
      id: deployment
      name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v1
name: Build and Publish Github Pages
on:
  repository_dispatch:
    types: trigger-ga___staticsite.yml
permissions:
  contents: read
  deployments: write
  id-token: write
  pages: write
